[package]
name = "free"
version = "0.1.0"
edition = "2024"
description = "Memory check tool"
license = "MIT"

[dependencies]
sysinfo = "0.35.1"

[profile.release]
codegen-units = 1
opt-level = "z"
strip = true
lto = true
